## Grading criteria


1 - correct code (on their inputs + manual check) - 10 points

2 - optimal running time ( o((m^3)) - 3 points

3 - sparse matrix representation - 3 points

4 - correct results on classical spaces - (! filtrations must be simplicial) - 3 points
    -- Draw our own filtrations and scan them
5 - correct interpretation of bar codes (bottom of the TD page) - 2 points

6 - clean-nes and tideness of code/explanations - [-2, 2] points

## Deadline - 7th February - 11:55 PM

In [53]:
class simplex:
    def __init__(self, line):
        self.dim, self.val, self.vert = self.parse_line(line)
    
    def parse_line(self, line):
        splited_line = line.split()
        val = float(splited_line[0])
        dim = int(splited_line[1])
        vert = [int(x) for x in splited_line[2:]]
        assert(len(vert)==dim+1)
        return dim, val, vert

def read_filtration(name):
    simplices = []
    with open(name, "r") as ins:
        for line in ins:
            simplices.append(simplex(line))
    return simplices

In [54]:
simplices = read_filtration('filtration.txt')

In [55]:
simplices.sort(key=lambda x: x.val)

In [56]:
for s in simplices:
    s.vert.sort()

In [57]:
for s in simplices:
    print s.dim, s.val, s.vert

0 1.0 [2]
0 1.0 [4]
0 1.0 [1]
1 2.0 [2, 4]
1 2.0 [1, 2]
0 3.0 [7]
1 4.0 [4, 7]
1 4.0 [1, 7]
1 5.0 [1, 4]
2 6.0 [1, 4, 7]


In [58]:
simplices_str =  [str(s.vert).strip('[]') for s in simplices]

In [59]:
d = {}
for i, s in enumerate(simplices_str):
    d[s] = i

In [60]:
print d

{'1, 2': 4, '4, 7': 6, '1, 7': 7, '1, 4': 8, '1': 2, '2': 0, '4': 1, '7': 5, '2, 4': 3, '1, 4, 7': 9}


In [92]:
sDict = {}
for i, s in enumeratb(simplices):
    sDict[i] = s

1.0


In [61]:
import numpy as np

In [62]:
s_matrix = np.zeros((len(simplices),len(simplices)))


In [63]:
for i, s in enumerate(simplices):
    if s.dim>0:
        vs = list(s.vert)
        for v in vs:
            temp = list(vs)
            temp.remove(v)
            #print temp
            s_matrix[d[str(temp).strip('[]')]][i] = 1          
        

[4]
[2]
[2]
[1]
[7]
[4]
[7]
[1]
[4]
[1]
[4, 7]
[1, 7]
[1, 4]


In [64]:
print s_matrix

[[ 0.  0.  0.  1.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  1.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  1.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


Question 2 (Reduction)

In [90]:
N = len(s_matrix)
low = [float('inf')]*N

for j in range(N):
    for i in range(N):
        auxI = N-i-1
        if s_matrix[auxI][j]==1:
            if auxI not in low[:j]:
                low[j] = auxI
            else:
                ind = low.index(auxI)
                s_matrix[:,j] = np.logical_xor(s_matrix[:,j],s_matrix[:,ind]).astype(int)
            break
            
for j in range(N):
    if low[j] == float('inf'):
        s_matrix[:,j] = np.zeros((1,N))

In [91]:
print s_matrix

[[ 0.  0.  0.  1.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


In [106]:
answer = []
for j in range(N):
    if low[j] == float('inf'):
        if j not in low:
            aux = sDict[j]
            answer.append(str(aux.dim)+' '+str(aux.val)+' '+'inf')
    else:
        aux1 = sDict[low[j]]
        aux2 = sDict[j]
        answer.append(str(aux1.dim)+' '+str(aux1.val)+' '+str(aux2.val))
print answer

['0 1.0 inf', '0 1.0 2.0', '0 1.0 2.0', '0 3.0 4.0', '1 4.0 inf', '1 5.0 6.0']
